### ISSUE TITLE
Accepted reliability filter throws error: an't adapt type 'QListWidgetItem'

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAVisualisation#1]
2017-11-09T09:36:26	1	Traceback (most recent call last):
			  File "C:\Users\stefan.blumentrath\.qgis-custom/python/plugins\NOFAVisualisation-master\nofa\gui\vis_dlg.py", line 368, in vis
			    self._get_col_str(vsbl_col_list))
			  File "C:\Users\stefan.blumentrath\.qgis-custom/python/plugins\NOFAVisualisation-master\nofa\db.py", line 2561, in get_vis_query
			    'muni_list': muni_list})
			ProgrammingError: can't adapt type 'QListWidgetItem'

**Comment by svoboond** [comment]
@ninsbl I would like to test it but my database account is not working anymore. Could you renew it?

**Comment by ninsbl** [comment]
@svoboond THanks for looking into this!
I just extended the validity of your db account!

**Comment by ninsbl** [comment]
@svoboond : Cool, thanks! I could not have done that in this quality ...
